all:
	make -C compressor
	make -C distortion
	make -C led
	make -C multidelay
	make -C verb

clean:
	make -C compressor clean
	make -C distortion clean
	make -C led clean
	make -C multidelay clean
	make -C verb clean
	
