# Project Name
TARGET = dfu

# Sources
CPP_SOURCES = ${TARGET}.cpp

# Library Locations
LIBDAISY_DIR = ../../../libdaisy
DAISYSP_DIR = ../../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

C_INCLUDES += -I../.. -I$(LIBDAISY_DIR)/src/sys

